apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: vlan-traffic-control-catalog
  # MUST be openshift-marketplace for OperatorHub UI visibility
  namespace: openshift-marketplace
spec:
  displayName: VLAN Traffic Control Operator Catalog
  publisher: Custom
  sourceType: grpc
  image: ghcr.io/rbruzzon73/vlan-traffic-control-catalog:v0.2.71
  updateStrategy:
    registryPoll:
      interval: 30m
