FROM golang:1.22 as builder
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o agent cmd/agent/main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
# Include iproute-tc explicitly for UBI9
RUN microdnf update -y && \
    microdnf install -y iproute iproute-tc ethtool procps-ng && \
    microdnf clean all
WORKDIR /
COPY --from=builder /workspace/agent /agent
USER 0
ENTRYPOINT ["/agent"]
