---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - nodes
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.med.io
  resources:
  - vlantrafficcontrolclasses
  - vlantrafficcontrols
  - vlantrafficcontrolsclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.med.io
  resources:
  - vlantrafficcontrolclasses/status
  - vlantrafficcontrols/status
  - vlantrafficcontrolsclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.med.io
  resources:
  - vlantrafficcontrols/finalizers
  verbs:
  - update
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
