//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HtbClassSpec) DeepCopyInto(out *HtbClassSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HtbClassSpec.
func (in *HtbClassSpec) DeepCopy() *HtbClassSpec {
	if in == nil {
		return nil
	}
	out := new(HtbClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HtbRootSpec) DeepCopyInto(out *HtbRootSpec) {
	*out = *in
	if in.Classes != nil {
		in, out := &in.Classes, &out.Classes
		*out = make([]VlanClassSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HtbRootSpec.
func (in *HtbRootSpec) DeepCopy() *HtbRootSpec {
	if in == nil {
		return nil
	}
	out := new(HtbRootSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanClassSpec) DeepCopyInto(out *VlanClassSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanClassSpec.
func (in *VlanClassSpec) DeepCopy() *VlanClassSpec {
	if in == nil {
		return nil
	}
	out := new(VlanClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanTrafficControl) DeepCopyInto(out *VlanTrafficControl) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanTrafficControl.
func (in *VlanTrafficControl) DeepCopy() *VlanTrafficControl {
	if in == nil {
		return nil
	}
	out := new(VlanTrafficControl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VlanTrafficControl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanTrafficControlList) DeepCopyInto(out *VlanTrafficControlList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VlanTrafficControl, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanTrafficControlList.
func (in *VlanTrafficControlList) DeepCopy() *VlanTrafficControlList {
	if in == nil {
		return nil
	}
	out := new(VlanTrafficControlList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VlanTrafficControlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanTrafficControlSpec) DeepCopyInto(out *VlanTrafficControlSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.HtbRoot.DeepCopyInto(&out.HtbRoot)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanTrafficControlSpec.
func (in *VlanTrafficControlSpec) DeepCopy() *VlanTrafficControlSpec {
	if in == nil {
		return nil
	}
	out := new(VlanTrafficControlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanTrafficControlStatus) DeepCopyInto(out *VlanTrafficControlStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanTrafficControlStatus.
func (in *VlanTrafficControlStatus) DeepCopy() *VlanTrafficControlStatus {
	if in == nil {
		return nil
	}
	out := new(VlanTrafficControlStatus)
	in.DeepCopyInto(out)
	return out
}
