//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActualNodeState) DeepCopyInto(out *ActualNodeState) {
	*out = *in
	if in.Classes != nil {
		in, out := &in.Classes, &out.Classes
		*out = make([]ClassSpec, len(*in))
		copy(*out, *in)
	}
	if in.IngressFilters != nil {
		in, out := &in.IngressFilters, &out.IngressFilters
		*out = make([]FilterMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActualNodeState.
func (in *ActualNodeState) DeepCopy() *ActualNodeState {
	if in == nil {
		return nil
	}
	out := new(ActualNodeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassSpec) DeepCopyInto(out *ClassSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassSpec.
func (in *ClassSpec) DeepCopy() *ClassSpec {
	if in == nil {
		return nil
	}
	out := new(ClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassStat) DeepCopyInto(out *ClassStat) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassStat.
func (in *ClassStat) DeepCopy() *ClassStat {
	if in == nil {
		return nil
	}
	out := new(ClassStat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDriftDelta) DeepCopyInto(out *ConfigDriftDelta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDriftDelta.
func (in *ConfigDriftDelta) DeepCopy() *ConfigDriftDelta {
	if in == nil {
		return nil
	}
	out := new(ConfigDriftDelta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterMeta) DeepCopyInto(out *FilterMeta) {
	*out = *in
	if in.Matches != nil {
		in, out := &in.Matches, &out.Matches
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterMeta.
func (in *FilterMeta) DeepCopy() *FilterMeta {
	if in == nil {
		return nil
	}
	out := new(FilterMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HtbRootSpec) DeepCopyInto(out *HtbRootSpec) {
	*out = *in
	if in.Classes != nil {
		in, out := &in.Classes, &out.Classes
		*out = make([]ClassSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HtbRootSpec.
func (in *HtbRootSpec) DeepCopy() *HtbRootSpec {
	if in == nil {
		return nil
	}
	out := new(HtbRootSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressStat) DeepCopyInto(out *IngressStat) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressStat.
func (in *IngressStat) DeepCopy() *IngressStat {
	if in == nil {
		return nil
	}
	out := new(IngressStat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceStats) DeepCopyInto(out *InterfaceStats) {
	*out = *in
	if in.ClassStats != nil {
		in, out := &in.ClassStats, &out.ClassStats
		*out = make([]ClassStat, len(*in))
		copy(*out, *in)
	}
	if in.IngressStats != nil {
		in, out := &in.IngressStats, &out.IngressStats
		*out = make([]IngressStat, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceStats.
func (in *InterfaceStats) DeepCopy() *InterfaceStats {
	if in == nil {
		return nil
	}
	out := new(InterfaceStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfigReport) DeepCopyInto(out *NodeConfigReport) {
	*out = *in
	in.Desired.DeepCopyInto(&out.Desired)
	in.Actual.DeepCopyInto(&out.Actual)
	if in.DriftDeltas != nil {
		in, out := &in.DriftDeltas, &out.DriftDeltas
		*out = make([]ConfigDriftDelta, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfigReport.
func (in *NodeConfigReport) DeepCopy() *NodeConfigReport {
	if in == nil {
		return nil
	}
	out := new(NodeConfigReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TolerationSpec) DeepCopyInto(out *TolerationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TolerationSpec.
func (in *TolerationSpec) DeepCopy() *TolerationSpec {
	if in == nil {
		return nil
	}
	out := new(TolerationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanTrafficControl) DeepCopyInto(out *VlanTrafficControl) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanTrafficControl.
func (in *VlanTrafficControl) DeepCopy() *VlanTrafficControl {
	if in == nil {
		return nil
	}
	out := new(VlanTrafficControl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VlanTrafficControl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanTrafficControlClass) DeepCopyInto(out *VlanTrafficControlClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanTrafficControlClass.
func (in *VlanTrafficControlClass) DeepCopy() *VlanTrafficControlClass {
	if in == nil {
		return nil
	}
	out := new(VlanTrafficControlClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VlanTrafficControlClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanTrafficControlClassList) DeepCopyInto(out *VlanTrafficControlClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VlanTrafficControlClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanTrafficControlClassList.
func (in *VlanTrafficControlClassList) DeepCopy() *VlanTrafficControlClassList {
	if in == nil {
		return nil
	}
	out := new(VlanTrafficControlClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VlanTrafficControlClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanTrafficControlClassSpec) DeepCopyInto(out *VlanTrafficControlClassSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanTrafficControlClassSpec.
func (in *VlanTrafficControlClassSpec) DeepCopy() *VlanTrafficControlClassSpec {
	if in == nil {
		return nil
	}
	out := new(VlanTrafficControlClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanTrafficControlList) DeepCopyInto(out *VlanTrafficControlList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VlanTrafficControl, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanTrafficControlList.
func (in *VlanTrafficControlList) DeepCopy() *VlanTrafficControlList {
	if in == nil {
		return nil
	}
	out := new(VlanTrafficControlList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VlanTrafficControlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanTrafficControlSpec) DeepCopyInto(out *VlanTrafficControlSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeLabelSelector != nil {
		in, out := &in.NodeLabelSelector, &out.NodeLabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]TolerationSpec, len(*in))
		copy(*out, *in)
	}
	in.HtbRoot.DeepCopyInto(&out.HtbRoot)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanTrafficControlSpec.
func (in *VlanTrafficControlSpec) DeepCopy() *VlanTrafficControlSpec {
	if in == nil {
		return nil
	}
	out := new(VlanTrafficControlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VlanTrafficControlStatus) DeepCopyInto(out *VlanTrafficControlStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveNodes != nil {
		in, out := &in.ActiveNodes, &out.ActiveNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VlanTrafficControlStatus.
func (in *VlanTrafficControlStatus) DeepCopy() *VlanTrafficControlStatus {
	if in == nil {
		return nil
	}
	out := new(VlanTrafficControlStatus)
	in.DeepCopyInto(out)
	return out
}
