apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: subnet200-localnet-udn
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: tc-virt-validation
  network:
    topology: Localnet
    localnet:
      physicalNetworkName: localnet-subnet200
      role: Secondary
      vlanID: 200
      subnets:
        - 10.200.0.0/24
