apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlan-traffic-control-manager
  namespace: openshift-vlan-tc-operator
  labels:
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: manager
        image: ghcr.io/rbruzzon73/vlan-traffic-control-manager:v0.2.0
        command:
        - /manager
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
