apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vlan-traffic-control-agent-role
rules:
  - apiGroups:
      - networking.med.io
    resources:
      - vlantrafficcontrols
      - vlantrafficcontrols/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vlan-traffic-control-agent-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vlan-traffic-control-agent-role
subjects:
  - kind: ServiceAccount
    name: vlan-traffic-control-agent-sa
    namespace: vlan-traffic-control-system
